### ISSUE TITLE
Adicionar Burger Menu

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#124]
UPDATED (15/04)

https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=2229%3A3301

UPDATE (15/04):
*Item de menu chamado COMO FUNCIONA?*
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=2229%3A3301

*Entrada para tutorial de consumidor na página de entrada*
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=2229%3A3294

*Flow LOJISTA - COMO FUNCIONA?*
Flow do Lojista, botão "ver como funciona?"
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=2229%3A3295

**Comment by trevisannatalia** [comment]
@SoniaQB @ritafalcao acho que no logo do naFila dentro do menu, deveria haver um link para a home também certo!?

@sexta13 alguns problemas:
- No ecrã com o cartaz o menu não está a funcionar
- @ritafalcao @SoniaQB no ecrã após login, onde consta: Ver fila ou Terminar fila, as imagens impossibilitam que o menu seja visto.

![firefox_qZG4EPSbTg](https://user-images.githubusercontent.com/17016676/84173432-311b7500-aa75-11ea-8901-27fe2ec04f90.png)

**Comment by sexta13** [comment]
Eu realmente tirei o menu de funcionar nessa página, mãe esqueci-me de fazer o mm pro ícone.. bem visto

**Comment by ritafalcao** [comment]
esta página não está conforme o design desktop. @SoniaQB é capaz de haver algumas coisas ainda desactualizadas neste ecrã. @xicosantos98 
<img width="545" alt="Captura de ecrã 2020-06-10, às 00 49 28" src="https://user-images.githubusercontent.com/4452719/84211865-4a8fe180-aab4-11ea-9212-434c3447401b.png">
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=2229%3A3295

**Comment by sexta13** [comment]
entao eu vou só corrigir a parte do cartaz ...ou seja esconder o icon do menu lá....depois qd se pegar neste layout, o problema desaparece :P

**Comment by joycef2110** [comment]
@sexta13 Ficou ok o cartaz, entretanto, quando abro o ecrã com o cartaz e volto para o ecrã anterior, o menu desaparece, e somente fazendo refresh volta.


![Capture2](https://user-images.githubusercontent.com/39491027/84365109-e448b300-abc8-11ea-81f2-d409c3b955e6.PNG)
![Capture](https://user-images.githubusercontent.com/39491027/84365118-e6127680-abc8-11ea-9186-ac596c1afbfb.PNG)

**Comment by sexta13** [comment]
@joycef2110 o fix foi abrir o cartaz num tab à parte, tal cm ta escrito no figma
