### ISSUE TITLE
Página de FAQ

### ISSUE THREAD

**Issue by rosanacaiado** [naFila-pt/nafila#138]

**Comment by carlosouro** [comment]
@ritafalcao @SoniaQB - suporte e comunicacao confirmaram que era bom ter esta pagina - ja temos conteudo? ou fica pra proxima sprint?

**Comment by ritafalcao** [comment]
Figma link:
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5456%3A33043
