### ISSUE TITLE
Nome da fila aparecer no titulo da pagina "queue" para ser mais fácil de identificar com varias tabs

### ISSUE THREAD

**Issue by rosanacaiado** [naFila-pt/nafila#145]

**Comment by trevisannatalia** [comment]
@xicosantos98 o mesmo não está a funcionar nos fluxos:
- Ao criar uma nova fila, o ecrã exibe o link sem a fila
- Ao informar a fila no flow do consumidor 

Único flow que está a funcionar é quando o consumidor acede ao link via QR code pois é com o cod da fila.

![firefox_4bPsCAWdpW](https://user-images.githubusercontent.com/17016676/84131897-1d541c80-aa3d-11ea-85a5-bc903bedef13.png)
