### ISSUE TITLE
Poster com QR code

### ISSUE THREAD

**Issue by rosanacaiado** [naFila-pt/nafila#148]

**Comment by trevisannatalia** [comment]
@carlosouro @luismendes535 Ao fazer o scan é exibido o link: dev.nafila.pt/tirar-senha/SVWLG entretanto o mesmo redireciona para a tela onde devo informar o codigo, conforme abaixo.

![WhatsApp Image 2020-06-05 at 00 32 39](https://user-images.githubusercontent.com/17016676/83820299-3a4ac180-a6c4-11ea-894f-0b3c6ae2233a.jpeg)
![WhatsApp Image 2020-06-05 at 00 32 40](https://user-images.githubusercontent.com/17016676/83820301-3b7bee80-a6c4-11ea-8de8-684a0ceb4e37.jpeg)

**Comment by ritafalcao** [comment]
update de esquadria de limitação do QR Code, cf. Design:

!! o que é para alterar tem bolinhas verdes https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5072%3A34312

**Comment by trevisannatalia** [comment]
@xicosantos98 Tanto em chrome quanto em Firefox, o cartaz é exibido quebrado, entretanto o link do QR code está ok

![chrome_I0Up2fRomt](https://user-images.githubusercontent.com/17016676/84046053-7f5f4400-a9a1-11ea-81a3-135f1602e062.png)

**Comment by trevisannatalia** [comment]
No firefox ainda há quebra... Creio que devemos focar no figma e verificar o tamanho que o mesmo, pois o QR code é bem menor.

![firefox_DWyYjQfnaX](https://user-images.githubusercontent.com/17016676/84127229-e1b65400-aa36-11ea-9c61-768f7c2ef895.png)
