### ISSUE TITLE
Assignar user properties de Google Analytics de identificação às Filas e Senha

### ISSUE THREAD

**Issue by rosanacaiado** [naFila-pt/nafila#162]
There are 3 user properties in Google analytics to enable traffic data filtering and custom reports, these can be set in the /users/{userId} document manually in the firestore database.

Practical example:
- .shop = "JCS-cascaisshopping"
- .retailerGroup = "JCS"
- .shoppingCentre = " cascaisshopping"

After this is setup, any queues created by the user, customers and tickets from those queues (all session activity related to that queue) will be appended with these user properties to google analytics.

These new properties should then appear in the custom reports in the Google analytics dashboard to use as filtering

**Comment by carlosouro** [comment]
@joycef2110 - nota que de acordo com o #180 , o `.shop` vai mudar ligeiramente e vai ser automaticamente preenchido (nao é preciso adicionar na base dados), com o `userId` da loja. Tou a trabalhar nas alteracoes neste momento
Se precisares comunica que eu explico os detalhes.
