### ISSUE TITLE
Alinhar textos da Política de Privacidade

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#171]
1) Aceder a Politica de Privacidade

Resultado atual: O texto nao esta alinhado com o ecrã

iOS e Mac -Safari
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30121/83512220-cd6ad800-a4c7-11ea-9c1f-6eacae00c4f1.png">

**Comment by joycef2110** [comment]
testado em windows e macOs. 
Chrome e Safari. Corrigido!
