### ISSUE TITLE
Alinhar textos Termos e Condicões

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#172]
Passos para reproduzir:
1) Entrar em termos e condicões

Resultado atual: TExto nao esta organizado

Browser: Safari
Device: iPhone 7
![IMG_4C4822330598-1 jpeg](https://user-images.githubusercontent.com/30121/83512406-0f941980-a4c8-11ea-8e9c-356cecb675e5.jpg)

**Comment by joycef2110** [comment]
testado e corrigido. 
iPhone Xs - 13.5
