### ISSUE TITLE
Footer esta no topo dos botões Gerar Senha e Terminar fila

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#174]
Passos para reproduzir:
1) Entrar na Aplicação como lojista
2) Criar fila

Resultado atual: Footer esta no topo dos botões Gerar Senha e Terminar fila
Browser: Chrome/Safari
Device: Mac OS
<img width="1434" alt="Screenshot_2020-05-31_at_22 17 52" src="https://user-images.githubusercontent.com/30121/83512778-9c3ed780-a4c8-11ea-9670-b55017e0bebc.png">

**Comment by smesab** [comment]
<img width="1439" alt="Screenshot 2020-06-03 at 14 36 40" src="https://user-images.githubusercontent.com/48382709/83643267-bac7d000-a5a7-11ea-8654-6491aca17f32.png">
Em Safari continua o issue. @trevisannatalia

**Comment by smesab** [comment]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/48382709/83643413-e5b22400-a5a7-11ea-85a2-8eb1be822dc4.png">

EM Chrome esta ok

**Comment by carlosouro** [comment]
aberto outro ticket para o problema so em Safari - a fechar este
