### ISSUE TITLE
Quebra layout flow consumidor mobile

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#176]
1) Aceder ao fluxo de consumidor
2) Navegar pelo onboarding
2) Informar um cod de fila

Resultado atual: O onboarding exibe um scroll horizontal, o nome da fila com quebra de layout, o ecrã informativo com a próxima senha também está com quebra de layout e não é possível fazer a retirada de senha, pois os assets ficam todos sobrepostos

Resultado esperado: O nome da fila deve ter espaçamento correto entre as linhas e deve ser possível informar o telemóvel para retirada de senha.

iOS - Iphone 8 (safari + chrome)

![4AC6E4CA-5252-4057-8271-AED1022149FC](https://user-images.githubusercontent.com/30121/83513070-1bcca680-a4c9-11ea-8d29-f26fe5f844b7.png)

![4E25475B-5BEB-414A-BF1D-0FE6E897BC08](https://user-images.githubusercontent.com/30121/83513108-29822c00-a4c9-11ea-9c53-80e32c05fd44.png)

![IMG_F5358C3CB6E1-1 jpeg](https://user-images.githubusercontent.com/30121/83513122-343cc100-a4c9-11ea-8352-6a1d86bafd24.jpg)

![Image_from_iOS_(2)](https://user-images.githubusercontent.com/30121/83513145-3ef75600-a4c9-11ea-9a6a-9edc11f41e32.png)

**Comment by smesab** [comment]
corrigido e testado.
