### ISSUE TITLE
Desktop não ter flow pra parte "Inserir codigo da loja"

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#177]
Na versão desktop eu consigo entrar na parte de inserir código da loja e isso ainda não deveria acontecer.

O "como funciona" em desktop nao deve levar ao "tirar senha" - a funcionalidade "tirar senha" nao deve de todo estar disponivel em desktop

**Comment by smesab** [comment]
tested in Mac
Browsers: Chrome/Safari

**Comment by joycef2110** [comment]
corrigido e testado.
