### ISSUE TITLE
SMS polling (inbound) sometimes takes a long time

### ISSUE THREAD

**Issue by carlosouro** [naFila-pt/nafila#178]

**Comment by smesab** [comment]
Quanto é muito tempo?

**Comment by carlosouro** [comment]
Estava a demorar 30-40 segundos as vezes a ter resposta.

Não é suposto demorar mais de 15 segundos (assumindo q n há problemas de
rede mobile).
O normal será ser rápido (3-7 segundos)

**Comment by smesab** [comment]
5 provas. Todas demoraram menos de 10 segundos
