### ISSUE TITLE
Ecrã acompanhamento de senha não está a funcionar

### ISSUE THREAD

**Issue by trevisannatalia** [naFila-pt/nafila#183]
1) Aceder dev.nafila.pt
2) Informar telemóvel
3) Confirmar retirada de senha

Resultado atual: Ecrã fica vazio
Resultado esperado: Ecrã exibe quantas senhas estão na frente e qual o número da senha retirada.

**Comment by trevisannatalia** [comment]
![Image from iOS (3)](https://user-images.githubusercontent.com/17016676/83576327-667e0b00-a529-11ea-9af7-e0a9bf259c28.png)

**Comment by smesab** [comment]
corrigido e testado.
