### ISSUE TITLE
Quebra layout no onboarding lojista

### ISSUE THREAD

**Issue by trevisannatalia** [naFila-pt/nafila#191]
- O título está com fon-size incorreto
- O espaçamento e quebra de linhas está incorreto em todos ecrãs.
- No primeiro ecrã o desenho do background está em cima da palavra nafila 
- É exibido uma faixa branca abaixo do footer amarelo (não deve existir essa faixa)

iPhone 8 - safari/chrome

**Comment by trevisannatalia** [comment]
![WhatsApp Image 2020-06-03 at 17 23 31](https://user-images.githubusercontent.com/17016676/83662224-22d5e080-a5bf-11ea-96e1-235b8cc6931a.jpeg)
![WhatsApp Image 2020-06-03 at 17 23 30 (1)](https://user-images.githubusercontent.com/17016676/83662225-236e7700-a5bf-11ea-9aff-a832f60be0ea.jpeg)
![WhatsApp Image 2020-06-03 at 17 23 30](https://user-images.githubusercontent.com/17016676/83662227-24070d80-a5bf-11ea-9d23-f9241ebe3747.jpeg)
![WhatsApp Image 2020-06-03 at 17 23 31 (1)](https://user-images.githubusercontent.com/17016676/83662230-249fa400-a5bf-11ea-946d-b3ab8ee1dce7.jpeg)

**Comment by ritafalcao** [comment]
Em desktop, o onboarding tem setas, fundos e títulos a saltar de local, de slide para slide.
