### ISSUE TITLE
Snackbar with blue background glow

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#201]
Snackbar of Lojista notice to call the next client has a blue glow that doesn't comply with the colour scheme.
![Imagem do iOS](https://user-images.githubusercontent.com/4452719/83684384-d8fcf280-a5de-11ea-81b3-9a952893cd7a.png)

**Comment by carlosouro** [comment]
@ritafalcao ok - agora é que tas mesmo a ficar sem bateria. já chega de testes! ಠ_ಠ
