### ISSUE TITLE
Counter allows to add more people than the tickets issued

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#202]

**Comment by carlosouro** [comment]
Tickets and counter are different things.

1 ticket can have 5 people (a family) coming into the store - it's one ticket only used but 5 people went in.

Also - in turn it's also possible the security guard let's someone in without a ticket so you can even have him using the counter without even dispensing tickets for the queue

**Comment by ritafalcao** [comment]
@carlosouro Yes, i removed from project once I realized that. delete it, please.
