### ISSUE TITLE
Logo link on header doesn't have return feedback

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#208]
On mouse hover, mouse action doesn't return feedback of hyperlink area.

**Comment by trevisannatalia** [comment]
@xicosantos98 está a faltar o hiperlink no logo do onboarding de lojista(https://dev.nafila.pt/lojista/como-funciona), e por favor, podes corrigir o tamanho do logo do onboarding do lojista para o mesmo tamanho que o onboarding do consumidor.

**Lojista**: https://dev.nafila.pt/lojista/como-funciona
**Consumidor**: https://dev.nafila.pt/como-funciona
