### ISSUE TITLE
Erase Data when password with less than 6 characters - register

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#210]
When entering data, and after entering password with less than 6 characters, the inserted data is automatically erased. Needs a hint for minimum password size.

**Comment by joycef2110** [comment]
@xicosantos98 , voltando o ticket para a correção:

"After entering password with less than 6 characters, the inserted data is automatically erased."

**Comment by joycef2110** [comment]
Testado no windows - Chrome
iPhone Xs - Chrome e Safari
