### ISSUE TITLE
"Terminar Sessão" changes side on the screen

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#213]
"Terminar Sessão" changes sides on the screen. Logo changes to left, but should be centered.

![Screenshot 2020-06-03 at 23 48 43](https://user-images.githubusercontent.com/4452719/83697176-40726c80-a5f6-11ea-865a-718420adde15.png)
![Uploading Screenshot 2020-06-03 at 23.47.18.png…]()

**Comment by carlosouro** [comment]
Will be made irrelevant due to terminao sessao moving now to burger menu
