### ISSUE TITLE
Terminar Fila - "Are you sure you want to quit?" Screens not comply with design

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#215]
When clicking on "Terminar Fila", the background of mobile is fuzzy and the desktop design does not comply with design.

**Comment by trevisannatalia** [comment]
@JNuno007 Ainda há um problema, pois está a exibir scroll horizontal.
![chrome_KJSBfVNFPt](https://user-images.githubusercontent.com/17016676/84042560-21306200-a99d-11ea-9e70-6cd3115fe7d9.png)
