### ISSUE TITLE
Change Sobre Page with Equipa and Texto Lojista

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#229]
Change Text on Suporte Lojistas has to change and update with new documents.

Change Layout in Sobre Page to accommodate Team list with links in each teammember.

https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5140%3A0

Links no docs: https://docs.google.com/spreadsheets/u/5/d/1mZfI3TM3ibPM_aTtEYJBqdyOKY1pTEU-tdiKc8NyJ5A/edit?usp=sharing

**Comment by SoniaQB** [comment]
- "Sobre" Page (with the "Equipa" section added):
[https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5140%3A0](url)

- Document with member links:
[https://docs.google.com/spreadsheets/d/1mZfI3TM3ibPM_aTtEYJBqdyOKY1pTEU-tdiKc8NyJ5A/edit#gid=0](url)
