### ISSUE TITLE
Change text on Suporte Lojistas

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#230]
Text on Suporte Lojistas has to change and update with new documents.

https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5140%3A0

**Comment by SoniaQB** [comment]
https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=3896%3A25949
