### ISSUE TITLE
Adapt Flows to include QR Code

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#236]
Flow de Consumidor adaptado ao uso de QR code:
!! o que é para alterar tem bolinhas verdes (https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5072%3A34312)

- [x] trocar conteúdo de 2 ecrãs em mobile
- [x]  trocar conteúdo de 2 ecrãs em desktop

**onboarding lojista mobile: corrections:** - ver imagens em anexo.
 - [x] O título está com font-size incorreto
- [x] O espaçamento e quebra de linhas está incorreto em todos os ecrãs.
- [x] No primeiro ecrã o desenho do background está em cima da palavra nafila
- [x] É exibido uma faixa branca abaixo do footer amarelo (não deve existir essa faixa)

**onboarding lojista desktop: corrections:**
- [x] desktop, o onboarding tem setas, fundos e títulos a saltar de local, de slide para slide. Ver design to comply.
![83662224-22d5e080-a5bf-11ea-96e1-235b8cc6931a](https://user-images.githubusercontent.com/4452719/83771819-97218a00-a67a-11ea-9311-9a0f7073e8c4.jpeg)

![83662227-24070d80-a5bf-11ea-9d23-f9241ebe3747](https://user-images.githubusercontent.com/4452719/83771837-9983e400-a67a-11ea-95ae-9b33dfd1f2c4.jpeg)
![83662225-236e7700-a5bf-11ea-9aff-a832f60be0
![83662230-249fa400-a5bf-11ea-946d-b3ab8ee1dce7](https://user-images.githubusercontent.com/4452719/83771839-9a1c7a80-a67a-11ea-925a-dd045e2422ca.jpeg)
ea](https://user-images.githubusercontent.com/4452719/83771829-98eb4d80-a67a-11ea-8413-a3b52dd01b24.jpeg)

**Comment by ritafalcao** [comment]
Flow de Consumidor adaptado ao uso de QR code + Cartaz HTML com QR Code:
!! o que é para alterar tem bolinhas verdes

- [ ] trocar conteúdo de 2 ecrãs em mobile 
- [ ] trocar conteúdo de 2 ecrãs em desktop
- [ ] acrescentar QR Code no cartaz HTML

https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5072%3A34312

**Comment by trevisannatalia** [comment]
@xicosantos98 @carlosouro Ainda há problemas de layout. (iphone 8 - safari)
- Font com tamanhos incorretos
- Quebra de linhas incorretas
- Texto com style bold incorreto
ps: Revisar todas correções que @ritafalcao solicitou, pois não estão de acordo.

Favor seguir os estilos/ tamanhos de acordo com figma - https://www.figma.com/file/Ny3rRkAQbvPJ5zSOYkIyLj/NAFILA?node-id=5190%3A0

![Image from iOS (5)](https://user-images.githubusercontent.com/17016676/84129957-85553380-aa3a-11ea-9fed-f39eb651b926.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/17016676/84129961-871ef700-aa3a-11ea-8da2-7658fa008922.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/17016676/84130669-76bb4c00-aa3b-11ea-81a7-7d44b4accd2f.png)
![Image from iOS (7)](https://user-images.githubusercontent.com/17016676/84130682-78850f80-aa3b-11ea-8a31-1ddc6b0cdc9d.png)
![Image from iOS (8)](https://user-images.githubusercontent.com/17016676/84130690-7ae76980-aa3b-11ea-8d14-94d9c0b896ef.png)
