### ISSUE TITLE
Phantom Queue: ao encerrar uma fila e voltar a abrir, com o ecrã de filas activo num outro ecrã, aparece duas vezes a mesma loja

### ISSUE THREAD

**Issue by ritafalcao** [naFila-pt/nafila#241]
A phantom queue stays visible in the public queue screen, after closing and beginning a queue on the same account.

Fechar e voltar a abrir a fila duplica a fila no ecra de status que esteja ja aberto

**Comment by sardyy** [comment]
I think this is fixed by #260, can be QA at the same time
